pipeline {
    agent any
 
    environment {
        // Define environment variables if needed
        DOCKER_HUB_CREDENTIALS = credentials('DockerhubCred')
        DOCKER_IMAGE_NAME = '1almamun/aws_docker_example'
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {
        stage('Start') {
            steps {
                echo 'Pipeline start.'
            }
        }
        stage('Build Docker Image') {
            steps {
                // Build and tag Docker image
                sh "docker build -t \$DOCKER_IMAGE_NAME:\$DOCKER_IMAGE_TAG"
            }
        }
    
        stage('Build and Push Docker Image') {
            steps {
                script {
                    // Login to Docker Hub
                    withCredentials([string(credentialsId: 'DockerhubCred', variable: 'DOCKER_HUB_CREDENTIALS')]) {
                        sh "docker login -u \$DOCKER_HUB_CREDENTIALS_USR -p \$DOCKER_HUB_CREDENTIALS_PSW"
                    }
 
                    // Build and tag Docker image
                    sh "docker build -t \$DOCKER_IMAGE_NAME:\$DOCKER_IMAGE_TAG ./aws_docker_example/"
 
                    // Push Docker image to Docker Hub
                    sh "docker push \$DOCKER_IMAGE_NAME:\$DOCKER_IMAGE_TAG"
                }
            }
        }
    }
 
    post {
        success {
            echo 'Docker image build and push successful!'
        }
        failure {
            error 'Docker image build or push failed!'
        }
    }
}